#!/bin/bash

echo "========================================"
echo "   VASTARA VERCEL SETUP GUIDE"
echo "========================================"
echo ""
echo "Your application is deployed but needs environment variables!"
echo ""
echo "📋 STEP-BY-STEP INSTRUCTIONS:"
echo ""
echo "1️⃣  Open Vercel Dashboard"
echo "   👉 https://vercel.com/dashboard"
echo ""
echo "2️⃣  Go to your project: abc"
echo "   👉 Click on your project name"
echo ""
echo "3️⃣  Navigate to Settings → Environment Variables"
echo "   👉 Click 'Settings' tab"
echo "   👉 Click 'Environment Variables' in sidebar"
echo ""
echo "4️⃣  Add these 4 environment variables:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable 1:"
echo "  Key: SHOPIFY_STORE_DOMAIN"
echo "  Value: kp0zf4-m0.myshopify.com"
echo "  Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable 2:"
echo "  Key: SHOPIFY_STOREFRONT_API_TOKEN"
echo "  Value: ab6268dc8176eddfee762646b4314689"
echo "  Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable 3:"
echo "  Key: SESSION_SECRET"
echo "  Value: 7iuZWUnmqZZHR+Gq7gKkSsDlb3dNSf5ei7DN5zVQXIQ="
echo "  Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable 4:"
echo "  Key: PUBLIC_STORE_URL"
echo "  Value: https://abc-git-main-andre-almeidas-projects.vercel.app"
echo "  Environments: ✓ Production ✓ Preview ✓ Development"
echo "  ⚠️  UPDATE THIS with your actual Vercel URL after first deployment!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "5️⃣  After adding all variables:"
echo "   👉 Click 'Deployments' tab"
echo "   👉 Click '...' menu on the latest deployment"
echo "   👉 Click 'Redeploy'"
echo "   👉 Check 'Use existing Build Cache'"
echo "   👉 Click 'Redeploy'"
echo ""
echo "✅ Your store will be live in 2-3 minutes!"
echo ""
echo "========================================"
echo "  Need help? Check VERCEL_ENV_SETUP.md"
echo "========================================"
